// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlrLwc5TzUZHLtKNg_PjSa92UVxmsyde0',
    appId: '1:65520815863:web:e47c23cb2316f21d3acdf2',
    messagingSenderId: '65520815863',
    projectId: 'registration-app-b2b61',
    authDomain: 'registration-app-b2b61.firebaseapp.com',
    storageBucket: 'registration-app-b2b61.firebasestorage.app',
    measurementId: 'G-E6R69DKT3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA19ma-mHWcvDEgJBivlD8LEXW1j67IWHk',
    appId: '1:65520815863:android:08d2258235e75db13acdf2',
    messagingSenderId: '65520815863',
    projectId: 'registration-app-b2b61',
    storageBucket: 'registration-app-b2b61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-lL8iTzalPsy4Ru2w43hcT35tW9uPJA',
    appId: '1:65520815863:ios:13fbce8f22670a0b3acdf2',
    messagingSenderId: '65520815863',
    projectId: 'registration-app-b2b61',
    storageBucket: 'registration-app-b2b61.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-lL8iTzalPsy4Ru2w43hcT35tW9uPJA',
    appId: '1:65520815863:ios:13fbce8f22670a0b3acdf2',
    messagingSenderId: '65520815863',
    projectId: 'registration-app-b2b61',
    storageBucket: 'registration-app-b2b61.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlrLwc5TzUZHLtKNg_PjSa92UVxmsyde0',
    appId: '1:65520815863:web:46678f0a5a79f5c33acdf2',
    messagingSenderId: '65520815863',
    projectId: 'registration-app-b2b61',
    authDomain: 'registration-app-b2b61.firebaseapp.com',
    storageBucket: 'registration-app-b2b61.firebasestorage.app',
    measurementId: 'G-N0KPJMBHCD',
  );
}
